version: '2.19'
networks:
  default:
    name: arr
    external: true
services:
  jellyfin:
    ports:
      - 8096:8096
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: 501:20
    network_mode: 'bridge'
    volumes:
      - /Users/sidd/Documents/jellyfin/dist:/jellyfin/jellyfin-web:ro
      - /Users/sidd/Documents/jellyfin/config:/config
      - /Users/sidd/Documents/jellyfin/cache:/cache
      - /Volumes/Elements/media:/media
      - /Volumes/Elements/data/media:/media2:ro
    restart: 'unless-stopped'
    environment:
        - PUID=501
        - PGID=20
        - UMASK=002
    # Optional - alternative address used for autodiscovery
  radarr:
    container_name: radarr
    image: cr.hotio.dev/hotio/radarr:latest
    restart: unless-stopped
    ports:
      - 7878:7878
    environment:
      - PUID=111
      - PGID=20
      - UMASK=002
    volumes:
      - /Users/sidd/Documents/jellyfin/arr_config/radarr:/config
      - /Volumes/Elements/data:/data
    depends_on:
      - prowlarr
      - qbittorrent
  sonarr:
    container_name: sonarr
    image: cr.hotio.dev/hotio/sonarr:latest
    restart: unless-stopped
    logging:
      driver: json-file
    ports:
      - 8989:8989
    environment:
      - PUID=222
      - PGID=20
      - UMASK=002
    volumes:
      - /Users/sidd/Documents/jellyfin/arr_config/sonarr:/config
      - /Volumes/Elements/data:/data
    depends_on:
      - prowlarr
      - qbittorrent

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=333
      - PGID=20
      - UMASK=002
      - WEBUI_PORT=8080
    volumes:
      - /Users/sidd/Documents/jellyfin/qbit_config:/config
      - /Volumes/Elements/data/torrents:/data/torrents/
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=333
      - PGID=20
      - UMASK=022
    volumes:
      - /Users/sidd/Documents/jellyfin/arr_config/prowlarr:/config
    ports:
      - 9696:9696
    restart: unless-stopped
    depends_on:
      - qbittorrent
  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    environment:
      - PUID=696
      - PGID=20
      - AUTO_UPDATE=true #optional
      - RUN_OPTS= #optional
    volumes:
      - /Users/sidd/Documents/jellyfin/jackett/config:/config
      - /Users/sidd/Documents/jellyfin/jackett/downloads:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped
  whisparr:
    container_name: whisparr
    image: cr.hotio.dev/hotio/whisparr
    ports:
      - "6969:6969"
    environment:
      - PUID=412
      - PGID=20
      - UMASK=002
    volumes:
      - /Users/sidd/Documents/jellyfin/arr_config/whisparr:/config
      - /Volumes/Elements/data:/data
    depends_on:
      - prowlarr
      - qbittorrent